# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo $LT_USERNAME
      echo $LT_ACCESS_KEY
      wget https://downloads.lambdatest.com/tunnel/v3/linux/64bit/LT_Linux.zip
      apt-get install unzip
      unzip LT_Linux.zip
      ./LT -user $LT_USERNAME -key $LT_ACCESS_KEY &
      sleep 30
 
  

- script: |
    npm install
    npm install -g protractor
    cd conf
    protractor parallel.conf.js
  continueOnError: true  
  displayName: 'npm install and build'

- task: stoptunnel@1
