# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'

variables:
  LT_USERNAME: neerajn
  LT_ACCESS_KEY: qJWmY51AY1vdlTC04Kh4iPttDsTgVl330z39YG4FadfqebaTSo

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'


- task: configuration@1
  inputs:
    connection: 'Demo Tunnel'
    isTunnelActivate: true
  
    
- script: |
    npm install
    npm install -g protractor
    cd conf
    protractor single.conf.js
  displayName: 'npm install and build'

- task: stoptunnel@1
