# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  LT_USERNAME: 'Your LambdaTest Username'
  LT_ACCESS_KEY: 'Your LambdaTest Access Key'

steps:
- task: configuration@1
  inputs:
    connection: 'Tunnel'
    isTunnelActivate: false
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g protractor
    cd conf
    protractor single.conf.js
  displayName: 'npm install and build'

- task: stoptunnel@1
